spring:
  profiles: "production"
  datasource:
  url: com.mysql.jdbc.Driver
  driverclassname: com.mysql.jdbc.Driver
---
spring:
  profiles:
    active: "develop"
  datasource:
    url: jdbc:h2:tcp://localhost/~/car
    driverclassname: org.h2.Driver
    username: root
    password: root
---







